//import React from "react";
//import { useState,useEffect } from "react";
//import Select from "react-dropdown-select";

export const data = [
    {
      id: 1,
       Claim_ID: '12345678',
      Name: 'Saravanan',
      Ailment: 'Heart Surgery',
      SLA: '25 %',
      P_TAT: '-',
      Stage: 'Discharge',
      Status: 'Pending Approval',
      Approved_Amount: 'Rs. 11,23,000',
      Hospital: 'Sant Parmanand Hospital',
    },
    {
        id: 2,
        Claim_ID: '12345678',
       Name: 'Saravanan',
       Ailment: 'Heart Surgery',
       SLA: '40 %',
       P_TAT: '2 Days',
       Stage: 'Final Claim',
       Status: 'Pending Approval',
       Approved_Amount: 'Rs. 11,23,000',
       Hospital: 'Apollo Multi Speciality Hospital',
    },
    {
        id: 3,
        Claim_ID: '12345678',
       Name: 'Saravanan',
       Ailment: 'Road Accident',
       SLA: '80 %',
       P_TAT: '-',
       Stage: 'Initial Authorization',
       Status: 'Pending Approval',
       Approved_Amount: 'Rs. 11,23,000',
       Hospital: 'MIOT Hospital',
    },
    {
        id: 4,
        Claim_ID: '12345678',
       Name: 'Saravanan',
       Ailment: 'Heart Surgery',
       SLA: '42 %',
       P_TAT: '-',
       Stage: 'Discharge',
       Status: 'TPA Query',
       Approved_Amount: 'Rs. 11,23,000',
       Hospital: 'ABCDEF Hospital',
    },
    {
        id: 5,
        Claim_ID: '12345678',
       Name: 'Saravanan',
       Ailment: 'Heart Surgery',
       SLA: '55 %',
       P_TAT: '-',
       Stage: 'Enhancemet',
       Status: 'Pending Approval',
       Approved_Amount: 'Rs. 11,23,000',
       Hospital: 'ABCDEF Hospital',
    },
    {
        id: 6,
        Claim_ID: '5678912',
       Name: 'Devana',
       Ailment: 'Dialysis',
       SLA: '55 %',
       P_TAT: '-',
       Stage: 'Enhancemet',
       Status: 'Pending Approval',
       Approved_Amount: 'Rs. 13,23,000',
       Hospital: 'ABCDEF Hospital',
    },
    {
        id: 7,
        Claim_ID: '5678654',
       Name: 'Layana',
       Ailment: 'Kidney Transplant',
       SLA: '55 %',
       P_TAT: '-',
       Stage: 'Discharge',
       Status: 'TPA Query',
       Approved_Amount: 'Rs. 10,23,000',
       Hospital: 'MIOT Hospital',
    },
    {
        id: 8,
        Claim_ID: '9876654',
       Name: 'Shivangi',
       Ailment: 'Kidney Transplant',
       SLA: '50 %',
       P_TAT: '-',
       Stage: 'Discharge',
       Status: 'TPA Query',
       Approved_Amount: 'Rs. 14,000,000',
       Hospital: 'Apollo Hospital',
    },
    
  ];

  
            